// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#ifndef PROTOBUF_Packet_2eproto__INCLUDED
#define PROTOBUF_Packet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Packet_2eproto();
void protobuf_InitDefaults_Packet_2eproto();
void protobuf_AssignDesc_Packet_2eproto();
void protobuf_ShutdownFile_Packet_2eproto();

class Callback;
class FileData;
class Packet;
class SystemInformation;

// ===================================================================

class SystemInformation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SystemInformation) */ {
 public:
  SystemInformation();
  virtual ~SystemInformation();

  SystemInformation(const SystemInformation& from);

  inline SystemInformation& operator=(const SystemInformation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemInformation& default_instance();

  static const SystemInformation* internal_default_instance();

  void Swap(SystemInformation* other);

  // implements Message ----------------------------------------------

  inline SystemInformation* New() const { return New(NULL); }

  SystemInformation* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SystemInformation& from);
  void MergeFrom(const SystemInformation& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SystemInformation* other);
  void UnsafeMergeFrom(const SystemInformation& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 port = 1;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 1;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // required int32 disksize = 2;
  bool has_disksize() const;
  void clear_disksize();
  static const int kDisksizeFieldNumber = 2;
  ::google::protobuf::int32 disksize() const;
  void set_disksize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SystemInformation)
 private:
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_disksize();
  inline void clear_has_disksize();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::int32 disksize_;
  friend void  protobuf_InitDefaults_Packet_2eproto_impl();
  friend void  protobuf_AddDesc_Packet_2eproto_impl();
  friend void protobuf_AssignDesc_Packet_2eproto();
  friend void protobuf_ShutdownFile_Packet_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SystemInformation> SystemInformation_default_instance_;

// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Packet) */ {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  static const Packet* internal_default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  inline Packet* New() const { return New(NULL); }

  Packet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Packet* other);
  void UnsafeMergeFrom(const Packet& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 FLAG = 1;
  bool has_flag() const;
  void clear_flag();
  static const int kFLAGFieldNumber = 1;
  ::google::protobuf::int32 flag() const;
  void set_flag(::google::protobuf::int32 value);

  // optional .SystemInformation sysinfo = 2;
  bool has_sysinfo() const;
  void clear_sysinfo();
  static const int kSysinfoFieldNumber = 2;
  const ::SystemInformation& sysinfo() const;
  ::SystemInformation* mutable_sysinfo();
  ::SystemInformation* release_sysinfo();
  void set_allocated_sysinfo(::SystemInformation* sysinfo);

  // optional .FileData fileData = 3;
  bool has_filedata() const;
  void clear_filedata();
  static const int kFileDataFieldNumber = 3;
  const ::FileData& filedata() const;
  ::FileData* mutable_filedata();
  ::FileData* release_filedata();
  void set_allocated_filedata(::FileData* filedata);

  // optional .Callback callback = 4;
  bool has_callback() const;
  void clear_callback();
  static const int kCallbackFieldNumber = 4;
  const ::Callback& callback() const;
  ::Callback* mutable_callback();
  ::Callback* release_callback();
  void set_allocated_callback(::Callback* callback);

  // @@protoc_insertion_point(class_scope:Packet)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_sysinfo();
  inline void clear_has_sysinfo();
  inline void set_has_filedata();
  inline void clear_has_filedata();
  inline void set_has_callback();
  inline void clear_has_callback();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::SystemInformation* sysinfo_;
  ::FileData* filedata_;
  ::Callback* callback_;
  ::google::protobuf::int32 flag_;
  friend void  protobuf_InitDefaults_Packet_2eproto_impl();
  friend void  protobuf_AddDesc_Packet_2eproto_impl();
  friend void protobuf_AssignDesc_Packet_2eproto();
  friend void protobuf_ShutdownFile_Packet_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Packet> Packet_default_instance_;

// -------------------------------------------------------------------

class FileData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FileData) */ {
 public:
  FileData();
  virtual ~FileData();

  FileData(const FileData& from);

  inline FileData& operator=(const FileData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FileData& default_instance();

  static const FileData* internal_default_instance();

  void Swap(FileData* other);

  // implements Message ----------------------------------------------

  inline FileData* New() const { return New(NULL); }

  FileData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileData& from);
  void MergeFrom(const FileData& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileData* other);
  void UnsafeMergeFrom(const FileData& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string filename = 1;
  bool has_filename() const;
  void clear_filename();
  static const int kFilenameFieldNumber = 1;
  const ::std::string& filename() const;
  void set_filename(const ::std::string& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  ::std::string* mutable_filename();
  ::std::string* release_filename();
  void set_allocated_filename(::std::string* filename);

  // required bytes data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional int32 block = 3;
  bool has_block() const;
  void clear_block();
  static const int kBlockFieldNumber = 3;
  ::google::protobuf::int32 block() const;
  void set_block(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:FileData)
 private:
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_block();
  inline void clear_has_block();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr filename_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 block_;
  friend void  protobuf_InitDefaults_Packet_2eproto_impl();
  friend void  protobuf_AddDesc_Packet_2eproto_impl();
  friend void protobuf_AssignDesc_Packet_2eproto();
  friend void protobuf_ShutdownFile_Packet_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<FileData> FileData_default_instance_;

// -------------------------------------------------------------------

class Callback : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Callback) */ {
 public:
  Callback();
  virtual ~Callback();

  Callback(const Callback& from);

  inline Callback& operator=(const Callback& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Callback& default_instance();

  static const Callback* internal_default_instance();

  void Swap(Callback* other);

  // implements Message ----------------------------------------------

  inline Callback* New() const { return New(NULL); }

  Callback* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Callback& from);
  void MergeFrom(const Callback& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Callback* other);
  void UnsafeMergeFrom(const Callback& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool success = 1;
  bool has_success() const;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // required int32 op = 2;
  bool has_op() const;
  void clear_op();
  static const int kOpFieldNumber = 2;
  ::google::protobuf::int32 op() const;
  void set_op(::google::protobuf::int32 value);

  // optional int32 filesize = 3;
  bool has_filesize() const;
  void clear_filesize();
  static const int kFilesizeFieldNumber = 3;
  ::google::protobuf::int32 filesize() const;
  void set_filesize(::google::protobuf::int32 value);

  // optional int32 block = 4;
  bool has_block() const;
  void clear_block();
  static const int kBlockFieldNumber = 4;
  ::google::protobuf::int32 block() const;
  void set_block(::google::protobuf::int32 value);

  // optional bytes data = 5;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 5;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:Callback)
 private:
  inline void set_has_success();
  inline void clear_has_success();
  inline void set_has_op();
  inline void clear_has_op();
  inline void set_has_filesize();
  inline void clear_has_filesize();
  inline void set_has_block();
  inline void clear_has_block();
  inline void set_has_data();
  inline void clear_has_data();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  bool success_;
  ::google::protobuf::int32 op_;
  ::google::protobuf::int32 filesize_;
  ::google::protobuf::int32 block_;
  friend void  protobuf_InitDefaults_Packet_2eproto_impl();
  friend void  protobuf_AddDesc_Packet_2eproto_impl();
  friend void protobuf_AssignDesc_Packet_2eproto();
  friend void protobuf_ShutdownFile_Packet_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Callback> Callback_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SystemInformation

// required int32 port = 1;
inline bool SystemInformation::has_port() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemInformation::set_has_port() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemInformation::clear_has_port() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemInformation::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 SystemInformation::port() const {
  // @@protoc_insertion_point(field_get:SystemInformation.port)
  return port_;
}
inline void SystemInformation::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:SystemInformation.port)
}

// required int32 disksize = 2;
inline bool SystemInformation::has_disksize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemInformation::set_has_disksize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemInformation::clear_has_disksize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SystemInformation::clear_disksize() {
  disksize_ = 0;
  clear_has_disksize();
}
inline ::google::protobuf::int32 SystemInformation::disksize() const {
  // @@protoc_insertion_point(field_get:SystemInformation.disksize)
  return disksize_;
}
inline void SystemInformation::set_disksize(::google::protobuf::int32 value) {
  set_has_disksize();
  disksize_ = value;
  // @@protoc_insertion_point(field_set:SystemInformation.disksize)
}

inline const SystemInformation* SystemInformation::internal_default_instance() {
  return &SystemInformation_default_instance_.get();
}
// -------------------------------------------------------------------

// Packet

// required int32 FLAG = 1;
inline bool Packet::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 Packet::flag() const {
  // @@protoc_insertion_point(field_get:Packet.FLAG)
  return flag_;
}
inline void Packet::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:Packet.FLAG)
}

// optional .SystemInformation sysinfo = 2;
inline bool Packet::has_sysinfo() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Packet::set_has_sysinfo() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Packet::clear_has_sysinfo() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Packet::clear_sysinfo() {
  if (sysinfo_ != NULL) sysinfo_->::SystemInformation::Clear();
  clear_has_sysinfo();
}
inline const ::SystemInformation& Packet::sysinfo() const {
  // @@protoc_insertion_point(field_get:Packet.sysinfo)
  return sysinfo_ != NULL ? *sysinfo_
                         : *::SystemInformation::internal_default_instance();
}
inline ::SystemInformation* Packet::mutable_sysinfo() {
  set_has_sysinfo();
  if (sysinfo_ == NULL) {
    sysinfo_ = new ::SystemInformation;
  }
  // @@protoc_insertion_point(field_mutable:Packet.sysinfo)
  return sysinfo_;
}
inline ::SystemInformation* Packet::release_sysinfo() {
  // @@protoc_insertion_point(field_release:Packet.sysinfo)
  clear_has_sysinfo();
  ::SystemInformation* temp = sysinfo_;
  sysinfo_ = NULL;
  return temp;
}
inline void Packet::set_allocated_sysinfo(::SystemInformation* sysinfo) {
  delete sysinfo_;
  sysinfo_ = sysinfo;
  if (sysinfo) {
    set_has_sysinfo();
  } else {
    clear_has_sysinfo();
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.sysinfo)
}

// optional .FileData fileData = 3;
inline bool Packet::has_filedata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Packet::set_has_filedata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Packet::clear_has_filedata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Packet::clear_filedata() {
  if (filedata_ != NULL) filedata_->::FileData::Clear();
  clear_has_filedata();
}
inline const ::FileData& Packet::filedata() const {
  // @@protoc_insertion_point(field_get:Packet.fileData)
  return filedata_ != NULL ? *filedata_
                         : *::FileData::internal_default_instance();
}
inline ::FileData* Packet::mutable_filedata() {
  set_has_filedata();
  if (filedata_ == NULL) {
    filedata_ = new ::FileData;
  }
  // @@protoc_insertion_point(field_mutable:Packet.fileData)
  return filedata_;
}
inline ::FileData* Packet::release_filedata() {
  // @@protoc_insertion_point(field_release:Packet.fileData)
  clear_has_filedata();
  ::FileData* temp = filedata_;
  filedata_ = NULL;
  return temp;
}
inline void Packet::set_allocated_filedata(::FileData* filedata) {
  delete filedata_;
  filedata_ = filedata;
  if (filedata) {
    set_has_filedata();
  } else {
    clear_has_filedata();
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.fileData)
}

// optional .Callback callback = 4;
inline bool Packet::has_callback() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Packet::set_has_callback() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Packet::clear_has_callback() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Packet::clear_callback() {
  if (callback_ != NULL) callback_->::Callback::Clear();
  clear_has_callback();
}
inline const ::Callback& Packet::callback() const {
  // @@protoc_insertion_point(field_get:Packet.callback)
  return callback_ != NULL ? *callback_
                         : *::Callback::internal_default_instance();
}
inline ::Callback* Packet::mutable_callback() {
  set_has_callback();
  if (callback_ == NULL) {
    callback_ = new ::Callback;
  }
  // @@protoc_insertion_point(field_mutable:Packet.callback)
  return callback_;
}
inline ::Callback* Packet::release_callback() {
  // @@protoc_insertion_point(field_release:Packet.callback)
  clear_has_callback();
  ::Callback* temp = callback_;
  callback_ = NULL;
  return temp;
}
inline void Packet::set_allocated_callback(::Callback* callback) {
  delete callback_;
  callback_ = callback;
  if (callback) {
    set_has_callback();
  } else {
    clear_has_callback();
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.callback)
}

inline const Packet* Packet::internal_default_instance() {
  return &Packet_default_instance_.get();
}
// -------------------------------------------------------------------

// FileData

// required string filename = 1;
inline bool FileData::has_filename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FileData::set_has_filename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FileData::clear_has_filename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FileData::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_filename();
}
inline const ::std::string& FileData::filename() const {
  // @@protoc_insertion_point(field_get:FileData.filename)
  return filename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileData::set_filename(const ::std::string& value) {
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FileData.filename)
}
inline void FileData::set_filename(const char* value) {
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FileData.filename)
}
inline void FileData::set_filename(const char* value, size_t size) {
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FileData.filename)
}
inline ::std::string* FileData::mutable_filename() {
  set_has_filename();
  // @@protoc_insertion_point(field_mutable:FileData.filename)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileData::release_filename() {
  // @@protoc_insertion_point(field_release:FileData.filename)
  clear_has_filename();
  return filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileData::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    set_has_filename();
  } else {
    clear_has_filename();
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:FileData.filename)
}

// required bytes data = 2;
inline bool FileData::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FileData::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FileData::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FileData::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& FileData::data() const {
  // @@protoc_insertion_point(field_get:FileData.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileData::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FileData.data)
}
inline void FileData::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FileData.data)
}
inline void FileData::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FileData.data)
}
inline ::std::string* FileData::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:FileData.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileData::release_data() {
  // @@protoc_insertion_point(field_release:FileData.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileData::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:FileData.data)
}

// optional int32 block = 3;
inline bool FileData::has_block() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FileData::set_has_block() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FileData::clear_has_block() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FileData::clear_block() {
  block_ = 0;
  clear_has_block();
}
inline ::google::protobuf::int32 FileData::block() const {
  // @@protoc_insertion_point(field_get:FileData.block)
  return block_;
}
inline void FileData::set_block(::google::protobuf::int32 value) {
  set_has_block();
  block_ = value;
  // @@protoc_insertion_point(field_set:FileData.block)
}

inline const FileData* FileData::internal_default_instance() {
  return &FileData_default_instance_.get();
}
// -------------------------------------------------------------------

// Callback

// required bool success = 1;
inline bool Callback::has_success() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Callback::set_has_success() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Callback::clear_has_success() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Callback::clear_success() {
  success_ = false;
  clear_has_success();
}
inline bool Callback::success() const {
  // @@protoc_insertion_point(field_get:Callback.success)
  return success_;
}
inline void Callback::set_success(bool value) {
  set_has_success();
  success_ = value;
  // @@protoc_insertion_point(field_set:Callback.success)
}

// required int32 op = 2;
inline bool Callback::has_op() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Callback::set_has_op() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Callback::clear_has_op() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Callback::clear_op() {
  op_ = 0;
  clear_has_op();
}
inline ::google::protobuf::int32 Callback::op() const {
  // @@protoc_insertion_point(field_get:Callback.op)
  return op_;
}
inline void Callback::set_op(::google::protobuf::int32 value) {
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:Callback.op)
}

// optional int32 filesize = 3;
inline bool Callback::has_filesize() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Callback::set_has_filesize() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Callback::clear_has_filesize() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Callback::clear_filesize() {
  filesize_ = 0;
  clear_has_filesize();
}
inline ::google::protobuf::int32 Callback::filesize() const {
  // @@protoc_insertion_point(field_get:Callback.filesize)
  return filesize_;
}
inline void Callback::set_filesize(::google::protobuf::int32 value) {
  set_has_filesize();
  filesize_ = value;
  // @@protoc_insertion_point(field_set:Callback.filesize)
}

// optional int32 block = 4;
inline bool Callback::has_block() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Callback::set_has_block() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Callback::clear_has_block() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Callback::clear_block() {
  block_ = 0;
  clear_has_block();
}
inline ::google::protobuf::int32 Callback::block() const {
  // @@protoc_insertion_point(field_get:Callback.block)
  return block_;
}
inline void Callback::set_block(::google::protobuf::int32 value) {
  set_has_block();
  block_ = value;
  // @@protoc_insertion_point(field_set:Callback.block)
}

// optional bytes data = 5;
inline bool Callback::has_data() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Callback::set_has_data() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Callback::clear_has_data() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Callback::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& Callback::data() const {
  // @@protoc_insertion_point(field_get:Callback.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Callback::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Callback.data)
}
inline void Callback::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Callback.data)
}
inline void Callback::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Callback.data)
}
inline ::std::string* Callback::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:Callback.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Callback::release_data() {
  // @@protoc_insertion_point(field_release:Callback.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Callback::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Callback.data)
}

inline const Callback* Callback::internal_default_instance() {
  return &Callback_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Packet_2eproto__INCLUDED
