/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SystemInfo.proto */

#ifndef PROTOBUF_C_SystemInfo_2eproto__INCLUDED
#define PROTOBUF_C_SystemInfo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SystemInfo SystemInfo;


/* --- enums --- */


/* --- messages --- */

struct  _SystemInfo
{
  ProtobufCMessage base;
  int32_t foldersize;
  int32_t port;
};
#define SYSTEM_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system_info__descriptor) \
    , 0, 0 }


/* SystemInfo methods */
void   system_info__init
                     (SystemInfo         *message);
size_t system_info__get_packed_size
                     (const SystemInfo   *message);
size_t system_info__pack
                     (const SystemInfo   *message,
                      uint8_t             *out);
size_t system_info__pack_to_buffer
                     (const SystemInfo   *message,
                      ProtobufCBuffer     *buffer);
SystemInfo *
       system_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system_info__free_unpacked
                     (SystemInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SystemInfo_Closure)
                 (const SystemInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor system_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SystemInfo_2eproto__INCLUDED */
